//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployWEBApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int Empno { get; set; }
        public string nam { get; set; }
        public string dept { get; set; }
        public string desig { get; set; }
        public Nullable<double> basic { get; set; }
    }
}
